03 lesson
Pavel-Galant/learning-javascript pull request #6
Opened 2020-05-21 06:27 UTC by Pavel-Galant

2020-05-21 07:45 UTC, arswarog requested changes

2020-05-21 07:45 UTC, arswarog commented on lesson-03/tests/01-sum-of-posistive.test.js
> +});
Отлично. Так же можно проверить массивы со специальными значениями типа number? такие как Infinity, NaN. Так же надо проверять и граничные условия, например - пустой массив

2020-05-21 07:45 UTC, arswarog commented on lesson-03/tests/02-word-stat.test.js
> +});
Надо проверять и на граничных данных, например пустая строка. Зачастую именно на граничных и появляются проблемы

2020-05-21 07:45 UTC, arswarog commented on lesson-03/tests/02-word-stat.test.js
> +});
Так же надо добавить проверки с граничными данными, например пустая строка или только пробелы

2020-05-21 08:04 UTC, Pavel-Galant commented on lesson-03/tests/01-sum-of-posistive.test.js
> +});
пустой массив был, остальное добавил.  насчет NaN и Infinity не сообразил )

2020-05-21 08:04 UTC, Pavel-Galant commented on lesson-03/tests/02-word-stat.test.js
> +});
исправл

2020-05-21 08:04 UTC, Pavel-Galant commented on lesson-03/tests/02-word-stat.test.js
> +});
исправил

2020-05-22 19:40 UTC, arswarog approved these changes

2020-05-22 20:35 UTC, merged